Repository test-fullautomation/robotframework-prometheus, pull requests merged in 2024-05, with the labels that each got.

#2 setup of repository infrastructure
  .gitattributes
  README.md
  README.rst
  additions/CExtendedSetup.py
  additions/__init__.py
  config/CRepositoryConfig.py
  config/__init__.py
  config/repository_config.json
  config/robotframework_aio/release_items_RobotframeworkExtensions.json
  dump_repository_config.py
  genpackagedoc.py
  packagedoc/additional_docs/Appendix.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.tex
  packagedoc/packagedoc_config.json
  prometheus_interface/__init__.py
  prometheus_interface/prometheus_interface.pdf
  prometheus_interface/prometheus_interface.py
  prometheus_interface/version.py
  readme.rst2md.py
  requirements.txt
  setup.py
Labels: enhancement, 0.12.1

#7 Added keywords 'inc_gauge' and 'dec_gauge'
  PrometheusInterface/PrometheusInterface.pdf
  PrometheusInterface/prometheus_interface.py
  PrometheusInterface/version.py
  README.md
  README.rst
  packagedoc/additional_docs/History.tex
  test/suite_2/gen_suite_files/gen_suite_files.py
  test/suite_2/grafana_settings/grafana_dashboard_2_settings.json
  test/suite_2/suite_2_A/__init__.robot
  test/suite_2/suite_2_A/tests/test_file_01_A.robot
  test/suite_2/suite_2_A/tests/test_file_02_A.robot
  test/suite_2/suite_2_A/tests/test_file_03_A.robot
  test/suite_2/suite_2_A/tests/test_file_04_A.robot
  test/suite_2/suite_2_A/tests/test_file_05_A.robot
  test/suite_2/suite_2_A/tests/test_file_06_A.robot
  test/suite_2/suite_2_A/tests/test_file_07_A.robot
  test/suite_2/suite_2_A/tests/test_file_08_A.robot
  test/suite_2/suite_2_A/tests/test_file_09_A.robot
  test/suite_2/suite_2_A/tests/test_file_10_A.robot
  test/suite_2/suite_2_A/tests/test_file_11_A.robot
  test/suite_2/suite_2_A/tests/test_file_12_A.robot
  test/suite_2/suite_2_A/tests/test_file_13_A.robot
  test/suite_2/suite_2_A/tests/test_file_14_A.robot
  test/suite_2/suite_2_A/tests/test_file_15_A.robot
  test/suite_2/suite_2_A/tests/test_file_16_A.robot
  test/suite_2/suite_2_A/tests/test_file_17_A.robot
  test/suite_2/suite_2_A/tests/test_file_18_A.robot
  test/suite_2/suite_2_A/tests/test_file_19_A.robot
  test/suite_2/suite_2_A/tests/test_file_20_A.robot
  test/suite_2/suite_2_B/__init__.robot
  test/suite_2/suite_2_B/tests/test_file_01_B.robot
  test/suite_2/suite_2_B/tests/test_file_02_B.robot
  test/suite_2/suite_2_B/tests/test_file_03_B.robot
  test/suite_2/suite_2_B/tests/test_file_04_B.robot
  test/suite_2/suite_2_B/tests/test_file_05_B.robot
  test/suite_2/suite_2_B/tests/test_file_06_B.robot
  test/suite_2/suite_2_B/tests/test_file_07_B.robot
  test/suite_2/suite_2_B/tests/test_file_08_B.robot
  test/suite_2/suite_2_B/tests/test_file_09_B.robot
  test/suite_2/suite_2_B/tests/test_file_10_B.robot
  test/suite_2/suite_2_B/tests/test_file_11_B.robot
  test/suite_2/suite_2_B/tests/test_file_12_B.robot
  test/suite_2/suite_2_B/tests/test_file_13_B.robot
  test/suite_2/suite_2_B/tests/test_file_14_B.robot
  test/suite_2/suite_2_B/tests/test_file_15_B.robot
  test/suite_2/suite_2_B/tests/test_file_16_B.robot
  test/suite_2/suite_2_B/tests/test_file_17_B.robot
  test/suite_2/suite_2_B/tests/test_file_18_B.robot
  test/suite_2/suite_2_B/tests/test_file_19_B.robot
  test/suite_2/suite_2_B/tests/test_file_20_B.robot
Labels: enhancement, 0.12.1

#10 Added interface description and some parts of the common description
  PrometheusInterface/PrometheusInterface.pdf
  PrometheusInterface/prometheus_interface.py
  PrometheusInterface/version.py
  README.md
  README.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.tex
Labels: documentation, 0.12.1

#11 Integrate some workflows into pipeline
  .github/workflows/release_to_pypi.yml
  .github/workflows/trigger_aio.yml
Labels: 0.12.1

#12 Adapted handling of library version and date; release info update
  PrometheusInterface/PrometheusInterface.pdf
  PrometheusInterface/prometheus_interface.py
  PrometheusInterface/version.py
  config/CRepositoryConfig.py
  config/robotframework_aio/release_items_PrometheusInterface.json
  packagedoc/additional_docs/History.tex
  test/suite_2/suite_2_A/__init__.robot
  test/suite_2/suite_2_B/__init__.robot
Labels: enhancement, 0.12.1
